### ISSUE TITLE
Selling shares procedure and bug

### ISSUE THREAD

**Issue by madoar** [freystef/Rails#14]
Lastly we found the action of selling shares including the director share sometimes strange.
In our case one player was selling 50% of his 60% Oldenburg shares, which were made up of the 20% director share and 4 10% shares. The problem was that the selling menu only showed him that he could sell 4 10% shares and not, 3 10% shares AND the 20% director share, what he wanted.
To see if the menu changes if we first sell 3 10% shares we tried that and recieved the following result:
![can t sell share](https://cloud.githubusercontent.com/assets/18488086/20775438/3be776e8-b75b-11e6-922b-3ef761eeecef.PNG)
After selling the last single 10% it was still possible to click on the sell button, even through the player only had the 20% director share left, which alone shouldn't be sellable.
When clicking on this share we recieved the following dialog:
![dump-oldenburg for 82](https://cloud.githubusercontent.com/assets/18488086/20775503/8dda1334-b75b-11e6-9ef3-60aa65b5cb1e.PNG)
Please ignore that the PD and maybe some other things changed in the second screenshot. This is because we also tried to some things to continue the game without selling the 20% director share but having a similar endresult.

**Comment by neutronc** [comment]
Good Day,

you cant sell a 20% share by rule. As long as there is a 10% share available that goes first and then you can sell another 10% as your 20% share will get automatically exchanged to a 10% share.
Regards,
Martin

**Comment by madoar** [comment]
Is this a part of the English rules, that 20% shares can't be sold?
In the german rules at the [Hans im Glück](http://www.hans-im-glueck.de/fileadmin/data_archive/Regeln/1835_Spielregel.pdf) website it's written on page 5:

> - Zu keinem Zeitpunk dürfen sich mehr als 50% einer jeweiligen Aktiengesellschaft im Bankpool befinden (Ausnahme: siehe Bankrott). Jedes "Papier" kann nur als Ganzes verkauft werden, nicht teilweise (z.B. durch den Austausch einer 20%-Aktie durch einen 10%-Anteil)
> - ...
> - Der Verkauf einer Direktor-Aktie ist ausschließelich dann möglich, wenn wenigstens ein anderer Spieler im Besitz einer direktionsfähigen Mehrheit ist (10% bei Preußen, sonst 20%).

The first bullet point I understand as it's actually possible to sell a 20% share. The only limitation is that it can ONLY be sold as a SINGLE share. Which means that the automatic trade of a 20% share to a 10% share, by selling 10% of the 20% share, is forbidden by the german rules.
The third bullet point narrows down the conditions of when you're able to sell a director share. It specifies that it's only possible to sell a director share if by it's sale another player has more shares than you, by which he becomes the new director.
