### ISSUE TITLE
Station placement bug in 18AL?

### ISSUE THREAD

**Issue by o0dano0o** [freystef/Rails#19]
It is TAG's turn in the OR and it is allowing me to place a station token in G4 and H3. Shouldn't these locations be blocked by ATN in H5?

Save game is here: 
[18al_station_bug.zip](https://github.com/freystef/Rails/files/1129127/18al_station_bug.zip)

![18al](https://user-images.githubusercontent.com/5915535/27930675-588096da-624c-11e7-9a50-1e0d84dae78c.JPG)

![18al-2](https://user-images.githubusercontent.com/5915535/27930905-1e7edf86-624d-11e7-9b15-860bb938c93e.JPG)

**Comment by neutronc** [comment]
I get a different picture, i am still allowed to place the +10 coal token though not an additional station token beyond the blocking token.i can only place a station token on hex g6 as per rule.

Need to investigate further.
Regards,
Martin

**Comment by neutronc** [comment]
Bug has been fixed, will be published in RC3
Thanks for reporting !
