### ISSUE TITLE
Selling counts as an action

### ISSUE THREAD

**Issue by madoar** [freystef/Rails#3]
Hi,
in addition to #2 we also observed another strange behaviour while playing 1835 that shouldn't occur.
In our game with three players we observed, that after 2 players passed in the stock round and the third player only sold a share, it was again the turn of the player who first passed to buy and/or sell a share, after which the the second and third player could do the same again.
Normally the game should then enter the first operation round instead of giving the first and second player the chance to buy the previously sold share of the first player to ensure the rise of the company whose share was sold previously by the third player.
![auswahl_046](https://cloud.githubusercontent.com/assets/18488086/16580636/a871d36a-42a5-11e6-8d6f-791a574772ed.png)

Greetings
Marc

**Comment by neutronc** [comment]
English and German Rules differ. The german rules explicitely state that a sale doesnt effect the turn end. Whereas the english rules say only if all players have passed does the round end.

**Comment by madoar** [comment]
Ok, so that's a difference in the rules between german rules and english rules, I understand.
Wouldn't it be useful to have an option in the setup-frame where you can select the rule version you want to use, like in our case german rules and english rules?
But I believe it may be quite hard to implement such rule differences and I'm also not sure if this is the only difference.
A few months ago my friends and me discovered another strange behaviour that doesn't conform with the german rules. 
The player that owned the companies M1 and M2 bought the first 4 train with the M1.
According to the german rules this enables him to start and **operate** the Preußen in exactly the same operation round. 
But if I remember correctly rails only allowed him to start the Preußen but didn't let him operate it in the same operation round, but only in the next one.
Because I don't know the english rules I'm not sure, but could this also be a rule difference between the german rules and the english rules?

**Comment by jdgalt** [comment]
This is debatable in the English rules.  There was a debate about it on Bill Stoll's site, and we wound up using the German rule.

The English rule, read literally, says the Prussian will operate that round unless at least one pre-PR private or minor company paid a dividend in the same round and was then traded-in.
